name: ideator_llava
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pandas
  - pillow
  - pip:
    - transformers==4.41.2
    - diffusers==0.30.0
    - accelerate==0.33.0
